/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedResultOfBusinessCalendarDto as NwfmSharedResultsPaginatedResultOfBusinessCalendarDto } from '../../models/NWFM/Shared/Results/paginated-result-of-business-calendar-dto';

export interface ApiWorkflowCalendarsGet$Params {
  page?: number;
  pageSize?: number;
  search?: string;
}

export function apiWorkflowCalendarsGet(http: HttpClient, rootUrl: string, params?: ApiWorkflowCalendarsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<NwfmSharedResultsPaginatedResultOfBusinessCalendarDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowCalendarsGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NwfmSharedResultsPaginatedResultOfBusinessCalendarDto>;
    })
  );
}

apiWorkflowCalendarsGet.PATH = '/api/workflow/calendars';
