/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddCalendarPeriodRequest as WorkflowApiControllersAddCalendarPeriodRequest } from '../../models/Workflow/Api/Controllers/add-calendar-period-request';
import { BusinessCalendarPeriodDto as WorkflowApplicationDtOsBusinessCalendarPeriodDto } from '../../models/Workflow/Application/DTOs/business-calendar-period-dto';

export interface ApiWorkflowCalendarsIdPeriodsPost$Params {
  id: string;
      body?: WorkflowApiControllersAddCalendarPeriodRequest
}

export function apiWorkflowCalendarsIdPeriodsPost(http: HttpClient, rootUrl: string, params: ApiWorkflowCalendarsIdPeriodsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsBusinessCalendarPeriodDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowCalendarsIdPeriodsPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsBusinessCalendarPeriodDto>;
    })
  );
}

apiWorkflowCalendarsIdPeriodsPost.PATH = '/api/workflow/calendars/{id}/periods';
