/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateBusinessCalendarRequest as WorkflowApiControllersCreateBusinessCalendarRequest } from '../../models/Workflow/Api/Controllers/create-business-calendar-request';
import { BusinessCalendarDto as WorkflowApplicationDtOsBusinessCalendarDto } from '../../models/Workflow/Application/DTOs/business-calendar-dto';

export interface ApiWorkflowCalendarsPost$Params {
      body?: WorkflowApiControllersCreateBusinessCalendarRequest
}

export function apiWorkflowCalendarsPost(http: HttpClient, rootUrl: string, params?: ApiWorkflowCalendarsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsBusinessCalendarDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowCalendarsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsBusinessCalendarDto>;
    })
  );
}

apiWorkflowCalendarsPost.PATH = '/api/workflow/calendars';
