/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddCalendarHolidayRequest as WorkflowApiControllersAddCalendarHolidayRequest } from '../../models/Workflow/Api/Controllers/add-calendar-holiday-request';
import { BusinessCalendarHolidayDto as WorkflowApplicationDtOsBusinessCalendarHolidayDto } from '../../models/Workflow/Application/DTOs/business-calendar-holiday-dto';

export interface ApiWorkflowCalendarsIdHolidaysPost$Params {
  id: string;
      body?: WorkflowApiControllersAddCalendarHolidayRequest
}

export function apiWorkflowCalendarsIdHolidaysPost(http: HttpClient, rootUrl: string, params: ApiWorkflowCalendarsIdHolidaysPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsBusinessCalendarHolidayDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowCalendarsIdHolidaysPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsBusinessCalendarHolidayDto>;
    })
  );
}

apiWorkflowCalendarsIdHolidaysPost.PATH = '/api/workflow/calendars/{id}/holidays';
