/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateBusinessCalendarRequest as WorkflowApiControllersUpdateBusinessCalendarRequest } from '../../models/Workflow/Api/Controllers/update-business-calendar-request';
import { BusinessCalendarDto as WorkflowApplicationDtOsBusinessCalendarDto } from '../../models/Workflow/Application/DTOs/business-calendar-dto';

export interface ApiWorkflowCalendarsIdPut$Params {
  id: string;
      body?: WorkflowApiControllersUpdateBusinessCalendarRequest
}

export function apiWorkflowCalendarsIdPut(http: HttpClient, rootUrl: string, params: ApiWorkflowCalendarsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsBusinessCalendarDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowCalendarsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsBusinessCalendarDto>;
    })
  );
}

apiWorkflowCalendarsIdPut.PATH = '/api/workflow/calendars/{id}';
