/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BusinessCalendarDto as WorkflowApplicationDtOsBusinessCalendarDto } from '../../models/Workflow/Application/DTOs/business-calendar-dto';

export interface ApiWorkflowCalendarsIdGet$Params {
  id: string;
}

export function apiWorkflowCalendarsIdGet(http: HttpClient, rootUrl: string, params: ApiWorkflowCalendarsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsBusinessCalendarDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowCalendarsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsBusinessCalendarDto>;
    })
  );
}

apiWorkflowCalendarsIdGet.PATH = '/api/workflow/calendars/{id}';
