import { definePreset } from '@primeng/themes';
import Aura from '@primeng/themes/aura';

export const WaterPreset = definePreset(Aura, {
  semantic: {
    primary: {
      50: '#f0f9fb',
      100: '#d8eff5',
      200: '#b3e0eb',
      300: '#7ecadc',
      400: '#45adc7',
      500: '#248fac',
      600: '#157591',
      700: '#145e77',
      800: '#164e62',
      900: '#164152',
      950: '#0a2a37',
    },
    focusRing: {
      width: '2px',
      style: 'solid',
      color: '{primary.color}',
      offset: '2px',
    },
    colorScheme: {
      light: {
        primary: {
          color: '{primary.600}',
          contrastColor: '#ffffff',
          hoverColor: '{primary.700}',
          activeColor: '{primary.800}',
        },
        highlight: {
          background: '{primary.50}',
          focusBackground: '{primary.100}',
          color: '{primary.800}',
          focusColor: '{primary.900}',
        },
        surface: {
          0: '#ffffff',
          50: '#f7fafb',
          100: '#eef3f5',
          200: '#e0e8ec',
          300: '#c9d5dc',
          400: '#94a7b1',
          500: '#647a86',
          600: '#4b5f6a',
          700: '#3a4b55',
          800: '#29363e',
          900: '#1a2329',
          950: '#0f161a',
        },
        text: {
          color: '{surface.900}',
          hoverColor: '{surface.950}',
          mutedColor: '{surface.500}',
          hoverMutedColor: '{surface.600}',
        },
        content: {
          background: '{surface.0}',
          hoverBackground: '{surface.100}',
          borderColor: '{surface.200}',
          color: '{text.color}',
          hoverColor: '{text.hoverColor}',
        },
        formField: {
          background: '{surface.0}',
          disabledBackground: '{surface.100}',
          filledBackground: '{surface.50}',
          borderColor: '{surface.300}',
          hoverBorderColor: '{surface.400}',
          focusBorderColor: '{primary.color}',
          invalidBorderColor: '{red.500}',
          color: '{surface.900}',
          disabledColor: '{surface.500}',
          placeholderColor: '{surface.500}',
        },
      },
      dark: {
        primary: {
          color: '{primary.400}',
          contrastColor: '{surface.950}',
          hoverColor: '{primary.300}',
          activeColor: '{primary.200}',
        },
        highlight: {
          background: 'color-mix(in srgb, {primary.400}, transparent 84%)',
          focusBackground: 'color-mix(in srgb, {primary.400}, transparent 76%)',
          color: 'rgba(255,255,255,0.9)',
          focusColor: 'rgba(255,255,255,0.9)',
        },
        surface: {
          0: '#ffffff',
          50: '#f0f5f7',
          100: '#d3e0e6',
          200: '#b0c3cc',
          300: '#8ba5b1',
          400: '#5f7d8b',
          500: '#405c69',
          600: '#2e4550',
          700: '#22343d',
          800: '#18242b',
          900: '#101a20',
          950: '#0a1116',
        },
        text: {
          color: '{surface.100}',
          hoverColor: '{surface.50}',
          mutedColor: '{surface.300}',
          hoverMutedColor: '{surface.200}',
        },
        content: {
          background: '{surface.800}',
          hoverBackground: '{surface.700}',
          borderColor: '{surface.700}',
          color: '{text.color}',
          hoverColor: '{text.hoverColor}',
        },
        formField: {
          background: '{surface.900}',
          disabledBackground: '{surface.700}',
          filledBackground: '{surface.800}',
          borderColor: '{surface.700}',
          hoverBorderColor: '{surface.600}',
          focusBorderColor: '{primary.color}',
          invalidBorderColor: '{red.400}',
          color: '{surface.100}',
          disabledColor: '{surface.400}',
          placeholderColor: '{surface.400}',
        },
      },
    },
  },
});
