/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TriggerEventEntry as WorkflowApplicationConstantsTriggerEventEntry } from '../../../../models/Workflow/Application/Constants/trigger-event-entry';
export interface EntityTypeEntry {
  entityType?: string | null;
  nameAr?: string | null;
  nameEn?: string | null;
  triggerEvents?: Array<WorkflowApplicationConstantsTriggerEventEntry> | null;
}
