/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntityTypeEntry as WorkflowApplicationConstantsEntityTypeEntry } from '../../../../models/Workflow/Application/Constants/entity-type-entry';
export interface ModuleCatalogEntry {
  entityTypes?: Array<WorkflowApplicationConstantsEntityTypeEntry> | null;
  moduleKey?: string | null;
  nameAr?: string | null;
  nameEn?: string | null;
}
