/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TriggerEventEntry {
  eventKey?: string | null;
  nameAr?: string | null;
  nameEn?: string | null;
  screenKey?: string | null;
}
