/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowParticipantDto as WorkflowApplicationDtOsWorkflowParticipantDto } from '../../models/Workflow/Application/DTOs/workflow-participant-dto';

export interface ApiWorkflowParticipantsIdGet$Params {
  id: string;
}

export function apiWorkflowParticipantsIdGet(http: HttpClient, rootUrl: string, params: ApiWorkflowParticipantsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowParticipantDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowParticipantsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowParticipantDto>;
    })
  );
}

apiWorkflowParticipantsIdGet.PATH = '/api/workflow/participants/{id}';
