/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegisterParticipantRequest as WorkflowApiControllersRegisterParticipantRequest } from '../../models/Workflow/Api/Controllers/register-participant-request';
import { WorkflowParticipantDto as WorkflowApplicationDtOsWorkflowParticipantDto } from '../../models/Workflow/Application/DTOs/workflow-participant-dto';

export interface ApiWorkflowParticipantsPost$Params {
      body?: WorkflowApiControllersRegisterParticipantRequest
}

export function apiWorkflowParticipantsPost(http: HttpClient, rootUrl: string, params?: ApiWorkflowParticipantsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowParticipantDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowParticipantsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowParticipantDto>;
    })
  );
}

apiWorkflowParticipantsPost.PATH = '/api/workflow/participants';
