/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowNotificationLogPageDto as WorkflowApplicationDtOsWorkflowNotificationLogPageDto } from '../../models/Workflow/Application/DTOs/workflow-notification-log-page-dto';

export interface ApiWorkflowNotificationsGet$Params {
  page?: number;
  pageSize?: number;
}

export function apiWorkflowNotificationsGet(http: HttpClient, rootUrl: string, params?: ApiWorkflowNotificationsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowNotificationLogPageDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowNotificationsGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowNotificationLogPageDto>;
    })
  );
}

apiWorkflowNotificationsGet.PATH = '/api/workflow/notifications';
