/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkItemDto as WorkflowApplicationDtOsWorkItemDto } from '../../models/Workflow/Application/DTOs/work-item-dto';

export interface ApiWorkflowWorkItemsMyGet$Params {
}

export function apiWorkflowWorkItemsMyGet(http: HttpClient, rootUrl: string, params?: ApiWorkflowWorkItemsMyGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkflowApplicationDtOsWorkItemDto>>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowWorkItemsMyGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkflowApplicationDtOsWorkItemDto>>;
    })
  );
}

apiWorkflowWorkItemsMyGet.PATH = '/api/workflow/work-items/my';
