/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DelegateWorkItemRequest as WorkflowApiControllersDelegateWorkItemRequest } from '../../models/Workflow/Api/Controllers/delegate-work-item-request';
import { WorkItemDto as WorkflowApplicationDtOsWorkItemDto } from '../../models/Workflow/Application/DTOs/work-item-dto';

export interface ApiWorkflowWorkItemsWorkItemIdDelegatePost$Params {
  workItemId: string;
      body?: WorkflowApiControllersDelegateWorkItemRequest
}

export function apiWorkflowWorkItemsWorkItemIdDelegatePost(http: HttpClient, rootUrl: string, params: ApiWorkflowWorkItemsWorkItemIdDelegatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkItemDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowWorkItemsWorkItemIdDelegatePost.PATH, 'post');
  if (params) {
    rb.path('workItemId', params.workItemId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkItemDto>;
    })
  );
}

apiWorkflowWorkItemsWorkItemIdDelegatePost.PATH = '/api/workflow/work-items/{workItemId}/delegate';
