/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompleteWorkItemRequest as WorkflowApiControllersCompleteWorkItemRequest } from '../../models/Workflow/Api/Controllers/complete-work-item-request';
import { WorkItemDto as WorkflowApplicationDtOsWorkItemDto } from '../../models/Workflow/Application/DTOs/work-item-dto';

export interface ApiWorkflowWorkItemsWorkItemIdCompletePost$Params {
  workItemId: string;
      body?: WorkflowApiControllersCompleteWorkItemRequest
}

export function apiWorkflowWorkItemsWorkItemIdCompletePost(http: HttpClient, rootUrl: string, params: ApiWorkflowWorkItemsWorkItemIdCompletePost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkItemDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowWorkItemsWorkItemIdCompletePost.PATH, 'post');
  if (params) {
    rb.path('workItemId', params.workItemId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkItemDto>;
    })
  );
}

apiWorkflowWorkItemsWorkItemIdCompletePost.PATH = '/api/workflow/work-items/{workItemId}/complete';
