/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkItemDto as WorkflowApplicationDtOsWorkItemDto } from '../../models/Workflow/Application/DTOs/work-item-dto';

export interface ApiWorkflowWorkItemsWorkItemIdClaimPost$Params {
  workItemId: string;
}

export function apiWorkflowWorkItemsWorkItemIdClaimPost(http: HttpClient, rootUrl: string, params: ApiWorkflowWorkItemsWorkItemIdClaimPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkItemDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowWorkItemsWorkItemIdClaimPost.PATH, 'post');
  if (params) {
    rb.path('workItemId', params.workItemId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkItemDto>;
    })
  );
}

apiWorkflowWorkItemsWorkItemIdClaimPost.PATH = '/api/workflow/work-items/{workItemId}/claim';
