const fs=require('fs'),path=require('path'); const root=path.resolve('backend');
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);}
function edit(p,fn){fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8')));}
for(const f of walk(root).filter(f=>f.endsWith('Controller.cs'))) edit(f,s=>s.replaceAll('=> TryGetOrganizationId(out orgId)','=> TryResolveTenant(out orgId)').replaceAll('JWT','application context').replaceAll('authenticated organization','active tenant').replaceAll('authenticated user','selected participant'));
edit('backend/src/Modules/Workflow/Workflow.Infrastructure/Persistence/WorkflowDbContextFactory.cs',s=>s.replace('Database=Privora_Dev','Database=NWFM'));
edit('backend/src/Modules/Workflow/Workflow.Application/Commands/RegisterParticipant/RegisterParticipantCommand.cs',s=>s.replace('Guid UserId,','string DisplayName,\n    string Email,\n    string? DisplayNameAr,'));
edit('backend/src/Modules/Workflow/Workflow.Application/Commands/RegisterParticipant/RegisterParticipantCommandValidator.cs',s=>s.replace('RuleFor(x => x.UserId).NotEmpty();','RuleFor(x => x.DisplayName).NotEmpty().MaximumLength(200);\n        RuleFor(x => x.DisplayNameAr).MaximumLength(200);\n        RuleFor(x => x.Email).NotEmpty().EmailAddress().MaximumLength(256);'));
edit('backend/src/Modules/Workflow/Workflow.Application/Commands/RegisterParticipant/RegisterParticipantCommandHandler.cs',s=>s.replace('    private readonly IWorkflowUserLookup _userLookup;\n','').replace('    private readonly IWorkflowUserLookup _userLookup;\r\n','').replace(/        IWorkflowUserLookup userLookup,\r?\n/,'').replace(/        _userLookup = userLookup;\r?\n/,'').replace(/        var alreadyExists =[\s\S]*?        var now =/,'        var now =').replaceAll('request.UserId','Guid.NewGuid()').replaceAll('userInfo.DisplayNameAr','request.DisplayNameAr').replaceAll('userInfo.DisplayName','request.DisplayName.Trim()').replaceAll('userInfo.Email','request.Email.Trim()'));
edit('backend/src/Modules/Workflow/Workflow.Api/Controllers/WorkflowParticipantsController.cs',s=>s.replace('orgId, request.UserId, request.EmployeeNumber','orgId, request.DisplayName, request.Email, request.DisplayNameAr, request.EmployeeNumber').replace('RegisterParticipantRequest(Guid UserId, string? EmployeeNumber)','RegisterParticipantRequest(string DisplayName, string Email, string? DisplayNameAr = null, string? EmployeeNumber = null)'));
edit('backend/src/Modules/Workflow/Workflow.Application/Constants/ModuleCatalog.cs',s=>`namespace Workflow.Application.Constants;\npublic static class ModuleCatalog\n{\n public static IReadOnlyList<ModuleCatalogEntry> GetAll() => [new("Standalone", "Standalone Workflow", "سير عمل مستقل", [new("WorkflowRequest", "Workflow Request", "طلب سير عمل", [new("RequestSubmitted", "Request Submitted", "تم تقديم الطلب", "workflow.start")])])];\n}\n`+s.slice(s.indexOf('public sealed record ModuleCatalogEntry')));
// No claims principal survives the extraction.
fs.unlinkSync('backend/src/Modules/Workflow/Workflow.Api/Controllers/WorkflowPrincipal.cs');
console.log('Backend context and direct participant registration adapted.');
