/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type ActivityType = 'Start' | 'End' | 'UserTask' | 'ExclusiveGateway' | 'ServiceTask' | 'Timer' | 'NotificationTask' | 'ParallelGateway' | 'JoinGateway' | 'ScriptTask' | 'WaitEvent' | 'InclusiveGateway' | 'CallActivity' | 'MainActivity';

