/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type WorkflowEventType = 'InstanceStarted' | 'InstanceCompleted' | 'InstanceCancelled' | 'InstanceFailed' | 'ActivityStarted' | 'ActivityCompleted' | 'ActivityFailed' | 'WorkItemClaimed' | 'WorkItemCompleted' | 'WorkItemCancelled' | 'TransitionTaken' | 'VariableSet' | 'InstanceSuspended' | 'InstanceResumed' | 'WorkItemReleased' | 'TimerScheduled' | 'TimerFired' | 'NotificationQueued' | 'NotificationFailed' | 'ServiceTaskExecuted' | 'ParallelBranchStarted' | 'ParallelBranchCompleted' | 'JoinCompleted' | 'IncidentOpened' | 'IncidentResolved' | 'ReminderSent' | 'EscalationApplied' | 'OutcomePublished' | 'CandidateAssigned' | 'WorkItemReassigned' | 'WorkItemDelegated';

