/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type WorkflowExecutionPolicy = 'StartNewInstance' | 'SignalExistingInstance' | 'StartIfNoRunningInstance' | 'RestartAfterTerminal';

