/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type WorkflowIncidentType = 'ServiceTaskFailed' | 'TimerFailed' | 'NotificationFailed' | 'UnhandledActivity' | 'IntegrationFailed' | 'SystemError';

