/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ModuleCatalogEntry as WorkflowApplicationConstantsModuleCatalogEntry } from '../../models/Workflow/Application/Constants/module-catalog-entry';

export interface ApiWorkflowModuleCatalogGet$Params {
}

export function apiWorkflowModuleCatalogGet(http: HttpClient, rootUrl: string, params?: ApiWorkflowModuleCatalogGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkflowApplicationConstantsModuleCatalogEntry>>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowModuleCatalogGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkflowApplicationConstantsModuleCatalogEntry>>;
    })
  );
}

apiWorkflowModuleCatalogGet.PATH = '/api/workflow/module-catalog';
