/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityInstanceStatus } from './Workflow/Domain/Enums/activity-instance-status';

/**
 * Each possible value of `ActivityInstanceStatus`
 */
export const ACTIVITY_INSTANCE_STATUS: ActivityInstanceStatus[] = [
  'Pending',
  'Active',
  'Completed',
  'Skipped',
  'Failed'
];