/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActionFailurePolicy } from './Workflow/Domain/Enums/action-failure-policy';

/**
 * Each possible value of `ActionFailurePolicy`
 */
export const ACTION_FAILURE_POLICY: ActionFailurePolicy[] = [
  'Continue',
  'Retry',
  'FailActivity',
  'FailWorkflow',
  'CreateIncident'
];