/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActionExecutionTrigger } from './Workflow/Domain/Enums/action-execution-trigger';

/**
 * Each possible value of `ActionExecutionTrigger`
 */
export const ACTION_EXECUTION_TRIGGER: ActionExecutionTrigger[] = [
  'OnEnter',
  'OnComplete',
  'OnOutcome',
  'OnFailure'
];