/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityType } from './Workflow/Domain/Enums/activity-type';

/**
 * Each possible value of `ActivityType`
 */
export const ACTIVITY_TYPE: ActivityType[] = [
  'Start',
  'End',
  'UserTask',
  'ExclusiveGateway',
  'ServiceTask',
  'Timer',
  'NotificationTask',
  'ParallelGateway',
  'JoinGateway',
  'ScriptTask',
  'WaitEvent',
  'InclusiveGateway',
  'CallActivity'
];