/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssignmentStrategy } from './Workflow/Domain/Enums/assignment-strategy';

/**
 * Each possible value of `AssignmentStrategy`
 */
export const ASSIGNMENT_STRATEGY: AssignmentStrategy[] = [
  'Manual',
  'RoundRobin',
  'LeastBusy',
  'Random',
  'FirstAvailable'
];