/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssigneeType } from './Workflow/Domain/Enums/assignee-type';

/**
 * Each possible value of `AssigneeType`
 */
export const ASSIGNEE_TYPE: AssigneeType[] = [
  'AssignmentGroup',
  'User',
  'Department',
  'Role',
  'Expression'
];