/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DayOfWeek } from './System/day-of-week';

/**
 * Each possible value of `DayOfWeek`
 */
export const DAY_OF_WEEK: DayOfWeek[] = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday'
];