/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SlaDurationUnit } from './Workflow/Domain/Enums/sla-duration-unit';

/**
 * Each possible value of `SlaDurationUnit`
 */
export const SLA_DURATION_UNIT: SlaDurationUnit[] = [
  'Minutes',
  'Hours',
  'BusinessHours',
  'Days',
  'BusinessDays'
];