/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VariableDataType } from './Workflow/Domain/Enums/variable-data-type';

/**
 * Each possible value of `VariableDataType`
 */
export const VARIABLE_DATA_TYPE: VariableDataType[] = [
  'String',
  'Integer',
  'Decimal',
  'Boolean',
  'Date',
  'DateTime',
  'Guid',
  'Json'
];