/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowTimerType } from './Workflow/Domain/Enums/workflow-timer-type';

/**
 * Each possible value of `WorkflowTimerType`
 */
export const WORKFLOW_TIMER_TYPE: WorkflowTimerType[] = [
  'DueDate',
  'Duration',
  'ExternalSignal'
];