/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowNotificationLogStatus } from './Workflow/Domain/Enums/workflow-notification-log-status';

/**
 * Each possible value of `WorkflowNotificationLogStatus`
 */
export const WORKFLOW_NOTIFICATION_LOG_STATUS: WorkflowNotificationLogStatus[] = [
  'Queued',
  'Logged',
  'Delivered',
  'Failed'
];