/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowTimerStatus } from './Workflow/Domain/Enums/workflow-timer-status';

/**
 * Each possible value of `WorkflowTimerStatus`
 */
export const WORKFLOW_TIMER_STATUS: WorkflowTimerStatus[] = [
  'Pending',
  'Fired',
  'Completed',
  'Cancelled',
  'Failed'
];