/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowInstanceStatus } from './Workflow/Domain/Enums/workflow-instance-status';

/**
 * Each possible value of `WorkflowInstanceStatus`
 */
export const WORKFLOW_INSTANCE_STATUS: WorkflowInstanceStatus[] = [
  'Pending',
  'Running',
  'Suspended',
  'Completed',
  'Cancelled',
  'Failed'
];