/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowVersionPolicy } from './Workflow/Domain/Enums/workflow-version-policy';

/**
 * Each possible value of `WorkflowVersionPolicy`
 */
export const WORKFLOW_VERSION_POLICY: WorkflowVersionPolicy[] = [
  'Latest',
  'Fixed'
];