/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowExecutionPolicy } from './Workflow/Domain/Enums/workflow-execution-policy';

/**
 * Each possible value of `WorkflowExecutionPolicy`
 */
export const WORKFLOW_EXECUTION_POLICY: WorkflowExecutionPolicy[] = [
  'StartNewInstance',
  'SignalExistingInstance',
  'StartIfNoRunningInstance',
  'RestartAfterTerminal'
];