/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowValidationStatus } from './Workflow/Domain/Enums/workflow-validation-status';

/**
 * Each possible value of `WorkflowValidationStatus`
 */
export const WORKFLOW_VALIDATION_STATUS: WorkflowValidationStatus[] = [
  'NotValidated',
  'Valid',
  'Invalid'
];