/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowBindingMode } from './Workflow/Domain/Enums/workflow-binding-mode';

/**
 * Each possible value of `WorkflowBindingMode`
 */
export const WORKFLOW_BINDING_MODE: WorkflowBindingMode[] = [
  'Disabled',
  'Shadow',
  'Active',
  'Paused'
];