/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowIncidentStatus } from './Workflow/Domain/Enums/workflow-incident-status';

/**
 * Each possible value of `WorkflowIncidentStatus`
 */
export const WORKFLOW_INCIDENT_STATUS: WorkflowIncidentStatus[] = [
  'Open',
  'InProgress',
  'Resolved',
  'Ignored'
];