/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowEventType } from './Workflow/Domain/Enums/workflow-event-type';

/**
 * Each possible value of `WorkflowEventType`
 */
export const WORKFLOW_EVENT_TYPE: WorkflowEventType[] = [
  'InstanceStarted',
  'InstanceCompleted',
  'InstanceCancelled',
  'InstanceFailed',
  'ActivityStarted',
  'ActivityCompleted',
  'ActivityFailed',
  'WorkItemClaimed',
  'WorkItemCompleted',
  'WorkItemCancelled',
  'TransitionTaken',
  'VariableSet',
  'InstanceSuspended',
  'InstanceResumed',
  'WorkItemReleased',
  'TimerScheduled',
  'TimerFired',
  'NotificationQueued',
  'NotificationFailed',
  'ServiceTaskExecuted',
  'ParallelBranchStarted',
  'ParallelBranchCompleted',
  'JoinCompleted',
  'IncidentOpened',
  'IncidentResolved',
  'ReminderSent',
  'EscalationApplied',
  'OutcomePublished',
  'CandidateAssigned',
  'WorkItemReassigned',
  'WorkItemDelegated'
];