/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowVersionStatus } from './Workflow/Domain/Enums/workflow-version-status';

/**
 * Each possible value of `WorkflowVersionStatus`
 */
export const WORKFLOW_VERSION_STATUS: WorkflowVersionStatus[] = [
  'Draft',
  'Published',
  'Retired'
];