/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkItemStatus } from './Workflow/Domain/Enums/work-item-status';

/**
 * Each possible value of `WorkItemStatus`
 */
export const WORK_ITEM_STATUS: WorkItemStatus[] = [
  'Pending',
  'Claimed',
  'Completed',
  'Cancelled'
];