/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowIncidentType } from './Workflow/Domain/Enums/workflow-incident-type';

/**
 * Each possible value of `WorkflowIncidentType`
 */
export const WORKFLOW_INCIDENT_TYPE: WorkflowIncidentType[] = [
  'ServiceTaskFailed',
  'TimerFailed',
  'NotificationFailed',
  'UnhandledActivity',
  'IntegrationFailed',
  'SystemError'
];