/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowIncidentSeverity } from './Workflow/Domain/Enums/workflow-incident-severity';

/**
 * Each possible value of `WorkflowIncidentSeverity`
 */
export const WORKFLOW_INCIDENT_SEVERITY: WorkflowIncidentSeverity[] = [
  'Low',
  'Medium',
  'High',
  'Critical'
];