/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowAssignmentGroupDto as WorkflowApplicationDtOsWorkflowAssignmentGroupDto } from '../../models/Workflow/Application/DTOs/workflow-assignment-group-dto';

export interface ApiWorkflowBindingsOrganizationsOrganizationIdGroupsGet$Params {
  organizationId: string;
}

export function apiWorkflowBindingsOrganizationsOrganizationIdGroupsGet(http: HttpClient, rootUrl: string, params: ApiWorkflowBindingsOrganizationsOrganizationIdGroupsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowAssignmentGroupDto>>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowBindingsOrganizationsOrganizationIdGroupsGet.PATH, 'get');
  if (params) {
    rb.path('organizationId', params.organizationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowAssignmentGroupDto>>;
    })
  );
}

apiWorkflowBindingsOrganizationsOrganizationIdGroupsGet.PATH = '/api/workflow/bindings/organizations/{organizationId}/groups';
