/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SimulateWorkflowBindingRequest as WorkflowApiControllersSimulateWorkflowBindingRequest } from '../../models/Workflow/Api/Controllers/simulate-workflow-binding-request';
import { WorkflowSimulationResultDto as WorkflowApplicationDtOsWorkflowSimulationResultDto } from '../../models/Workflow/Application/DTOs/workflow-simulation-result-dto';

export interface ApiWorkflowBindingsBindingIdSimulatePost$Params {
  bindingId: string;
      body?: WorkflowApiControllersSimulateWorkflowBindingRequest
}

export function apiWorkflowBindingsBindingIdSimulatePost(http: HttpClient, rootUrl: string, params: ApiWorkflowBindingsBindingIdSimulatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowSimulationResultDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowBindingsBindingIdSimulatePost.PATH, 'post');
  if (params) {
    rb.path('bindingId', params.bindingId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowSimulationResultDto>;
    })
  );
}

apiWorkflowBindingsBindingIdSimulatePost.PATH = '/api/workflow/bindings/{bindingId}/simulate';
