/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowBindingDto as WorkflowApplicationDtOsWorkflowBindingDto } from '../../models/Workflow/Application/DTOs/workflow-binding-dto';

export interface ApiWorkflowBindingsBindingIdGet$Params {
  bindingId: string;
}

export function apiWorkflowBindingsBindingIdGet(http: HttpClient, rootUrl: string, params: ApiWorkflowBindingsBindingIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowBindingDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowBindingsBindingIdGet.PATH, 'get');
  if (params) {
    rb.path('bindingId', params.bindingId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowBindingDto>;
    })
  );
}

apiWorkflowBindingsBindingIdGet.PATH = '/api/workflow/bindings/{bindingId}';
