/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowRequestPageDto as WorkflowApplicationQueriesListWorkflowRequestsWorkflowRequestPageDto } from '../../models/Workflow/Application/Queries/ListWorkflowRequests/workflow-request-page-dto';
import { WorkflowInstanceStatus as WorkflowDomainEnumsWorkflowInstanceStatus } from '../../models/Workflow/Domain/Enums/workflow-instance-status';

export interface ApiWorkflowRequestsGet$Params {
  page?: number;
  pageSize?: number;
  search?: string;
  status?: WorkflowDomainEnumsWorkflowInstanceStatus;
  service?: string;
  currentStep?: string;
  originalGroupId?: string;
  fromUtc?: string;
  toUtc?: string;
  slaStatus?: string;
  sortBy?: string;
}

export function apiWorkflowRequestsGet(http: HttpClient, rootUrl: string, params?: ApiWorkflowRequestsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationQueriesListWorkflowRequestsWorkflowRequestPageDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRequestsGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('search', params.search, {});
    rb.query('status', params.status, {});
    rb.query('service', params.service, {});
    rb.query('currentStep', params.currentStep, {});
    rb.query('originalGroupId', params.originalGroupId, {});
    rb.query('fromUtc', params.fromUtc, {});
    rb.query('toUtc', params.toUtc, {});
    rb.query('slaStatus', params.slaStatus, {});
    rb.query('sortBy', params.sortBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationQueriesListWorkflowRequestsWorkflowRequestPageDto>;
    })
  );
}

apiWorkflowRequestsGet.PATH = '/api/workflow/requests';
