/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowRequestDto as WorkflowApplicationDtOsWorkflowRequestDto } from '../../models/Workflow/Application/DTOs/workflow-request-dto';

export interface ApiWorkflowRequestsRequestIdGet$Params {
  requestId: string;
}

export function apiWorkflowRequestsRequestIdGet(http: HttpClient, rootUrl: string, params: ApiWorkflowRequestsRequestIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowRequestDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRequestsRequestIdGet.PATH, 'get');
  if (params) {
    rb.path('requestId', params.requestId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowRequestDto>;
    })
  );
}

apiWorkflowRequestsRequestIdGet.PATH = '/api/workflow/requests/{requestId}';
