/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowPublishPreviewDto as WorkflowApplicationDtOsWorkflowPublishPreviewDto } from '../../models/Workflow/Application/DTOs/workflow-publish-preview-dto';

export interface ApiWorkflowDefinitionsDefinitionIdVersionsVersionIdPublishPreviewGet$Params {
  definitionId: string;
  versionId: string;
}

export function apiWorkflowDefinitionsDefinitionIdVersionsVersionIdPublishPreviewGet(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsDefinitionIdVersionsVersionIdPublishPreviewGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowPublishPreviewDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsDefinitionIdVersionsVersionIdPublishPreviewGet.PATH, 'get');
  if (params) {
    rb.path('definitionId', params.definitionId, {});
    rb.path('versionId', params.versionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowPublishPreviewDto>;
    })
  );
}

apiWorkflowDefinitionsDefinitionIdVersionsVersionIdPublishPreviewGet.PATH = '/api/workflow/definitions/{definitionId}/versions/{versionId}/publish-preview';
