/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowVersionDto as WorkflowApplicationDtOsWorkflowVersionDto } from '../../models/Workflow/Application/DTOs/workflow-version-dto';

export interface ApiWorkflowDefinitionsDefinitionIdVersionsVersionIdPublishPost$Params {
  definitionId: string;
  versionId: string;
}

export function apiWorkflowDefinitionsDefinitionIdVersionsVersionIdPublishPost(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsDefinitionIdVersionsVersionIdPublishPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowVersionDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsDefinitionIdVersionsVersionIdPublishPost.PATH, 'post');
  if (params) {
    rb.path('definitionId', params.definitionId, {});
    rb.path('versionId', params.versionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowVersionDto>;
    })
  );
}

apiWorkflowDefinitionsDefinitionIdVersionsVersionIdPublishPost.PATH = '/api/workflow/definitions/{definitionId}/versions/{versionId}/publish';
