/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SaveWorkflowDraftXmlRequest as WorkflowApiControllersSaveWorkflowDraftXmlRequest } from '../../models/Workflow/Api/Controllers/save-workflow-draft-xml-request';
import { WorkflowVersionDto as WorkflowApplicationDtOsWorkflowVersionDto } from '../../models/Workflow/Application/DTOs/workflow-version-dto';

export interface ApiWorkflowDefinitionsDefinitionIdVersionsVersionIdXmlPut$Params {
  definitionId: string;
  versionId: string;
      body?: WorkflowApiControllersSaveWorkflowDraftXmlRequest
}

export function apiWorkflowDefinitionsDefinitionIdVersionsVersionIdXmlPut(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsDefinitionIdVersionsVersionIdXmlPut$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowVersionDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsDefinitionIdVersionsVersionIdXmlPut.PATH, 'put');
  if (params) {
    rb.path('definitionId', params.definitionId, {});
    rb.path('versionId', params.versionId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowVersionDto>;
    })
  );
}

apiWorkflowDefinitionsDefinitionIdVersionsVersionIdXmlPut.PATH = '/api/workflow/definitions/{definitionId}/versions/{versionId}/xml';
