/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateSlaPolicyRequest as WorkflowApiControllersUpdateSlaPolicyRequest } from '../../models/Workflow/Api/Controllers/update-sla-policy-request';
import { SlaPolicyDto as WorkflowApplicationDtOsSlaPolicyDto } from '../../models/Workflow/Application/DTOs/sla-policy-dto';

export interface ApiWorkflowSlaPoliciesIdPut$Params {
  id: string;
      body?: WorkflowApiControllersUpdateSlaPolicyRequest
}

export function apiWorkflowSlaPoliciesIdPut(http: HttpClient, rootUrl: string, params: ApiWorkflowSlaPoliciesIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsSlaPolicyDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowSlaPoliciesIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsSlaPolicyDto>;
    })
  );
}

apiWorkflowSlaPoliciesIdPut.PATH = '/api/workflow/sla-policies/{id}';
