/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkloadDashboardDto as WorkflowApplicationDtOsWorkloadDashboardDto } from '../../models/Workflow/Application/DTOs/workload-dashboard-dto';

export interface ApiWorkflowWorkloadGet$Params {
}

export function apiWorkflowWorkloadGet(http: HttpClient, rootUrl: string, params?: ApiWorkflowWorkloadGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkloadDashboardDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowWorkloadGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkloadDashboardDto>;
    })
  );
}

apiWorkflowWorkloadGet.PATH = '/api/workflow/workload';
