/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowBindingAssignmentMappingDto as WorkflowApplicationDtOsWorkflowBindingAssignmentMappingDto } from '../../models/Workflow/Application/DTOs/workflow-binding-assignment-mapping-dto';

export interface ApiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsGet$Params {
  definitionId: string;
  bindingId: string;
  organizationId: string;
}

export function apiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsGet(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowBindingAssignmentMappingDto>>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsGet.PATH, 'get');
  if (params) {
    rb.path('definitionId', params.definitionId, {});
    rb.path('bindingId', params.bindingId, {});
    rb.path('organizationId', params.organizationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowBindingAssignmentMappingDto>>;
    })
  );
}

apiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsGet.PATH = '/api/workflow/definitions/{definitionId}/bindings/{bindingId}/organizations/{organizationId}/mappings';
