/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateWorkflowBindingAssignmentMappingRequest as WorkflowApiControllersCreateWorkflowBindingAssignmentMappingRequest } from '../../models/Workflow/Api/Controllers/create-workflow-binding-assignment-mapping-request';
import { WorkflowBindingAssignmentMappingDto as WorkflowApplicationDtOsWorkflowBindingAssignmentMappingDto } from '../../models/Workflow/Application/DTOs/workflow-binding-assignment-mapping-dto';

export interface ApiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsPost$Params {
  definitionId: string;
  bindingId: string;
  organizationId: string;
      body?: WorkflowApiControllersCreateWorkflowBindingAssignmentMappingRequest
}

export function apiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsPost(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowBindingAssignmentMappingDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsPost.PATH, 'post');
  if (params) {
    rb.path('definitionId', params.definitionId, {});
    rb.path('bindingId', params.bindingId, {});
    rb.path('organizationId', params.organizationId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowBindingAssignmentMappingDto>;
    })
  );
}

apiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsPost.PATH = '/api/workflow/definitions/{definitionId}/bindings/{bindingId}/organizations/{organizationId}/mappings';
