/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedResultOfWorkflowBindingDto as NwfmSharedResultsPaginatedResultOfWorkflowBindingDto } from '../../models/NWFM/Shared/Results/paginated-result-of-workflow-binding-dto';

export interface ApiWorkflowDefinitionsDefinitionIdBindingsGet$Params {
  definitionId: string;
  page?: number;
  pageSize?: number;
}

export function apiWorkflowDefinitionsDefinitionIdBindingsGet(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsDefinitionIdBindingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<NwfmSharedResultsPaginatedResultOfWorkflowBindingDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsDefinitionIdBindingsGet.PATH, 'get');
  if (params) {
    rb.path('definitionId', params.definitionId, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NwfmSharedResultsPaginatedResultOfWorkflowBindingDto>;
    })
  );
}

apiWorkflowDefinitionsDefinitionIdBindingsGet.PATH = '/api/workflow/definitions/{definitionId}/bindings';
