/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateWorkflowBindingRequest as WorkflowApiControllersCreateWorkflowBindingRequest } from '../../models/Workflow/Api/Controllers/create-workflow-binding-request';
import { WorkflowBindingDto as WorkflowApplicationDtOsWorkflowBindingDto } from '../../models/Workflow/Application/DTOs/workflow-binding-dto';

export interface ApiWorkflowDefinitionsDefinitionIdBindingsPost$Params {
  definitionId: string;
      body?: WorkflowApiControllersCreateWorkflowBindingRequest
}

export function apiWorkflowDefinitionsDefinitionIdBindingsPost(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsDefinitionIdBindingsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowBindingDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsDefinitionIdBindingsPost.PATH, 'post');
  if (params) {
    rb.path('definitionId', params.definitionId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowBindingDto>;
    })
  );
}

apiWorkflowDefinitionsDefinitionIdBindingsPost.PATH = '/api/workflow/definitions/{definitionId}/bindings';
