/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowBindingDto as WorkflowApplicationDtOsWorkflowBindingDto } from '../../models/Workflow/Application/DTOs/workflow-binding-dto';

export interface ApiWorkflowDefinitionsDefinitionIdBindingsBindingIdGet$Params {
  definitionId: string;
  bindingId: string;
}

export function apiWorkflowDefinitionsDefinitionIdBindingsBindingIdGet(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsDefinitionIdBindingsBindingIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowBindingDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsDefinitionIdBindingsBindingIdGet.PATH, 'get');
  if (params) {
    rb.path('definitionId', params.definitionId, {});
    rb.path('bindingId', params.bindingId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowBindingDto>;
    })
  );
}

apiWorkflowDefinitionsDefinitionIdBindingsBindingIdGet.PATH = '/api/workflow/definitions/{definitionId}/bindings/{bindingId}';
