/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsMappingIdDelete$Params {
  definitionId: string;
  bindingId: string;
  organizationId: string;
  mappingId: string;
}

export function apiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsMappingIdDelete(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsMappingIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsMappingIdDelete.PATH, 'delete');
  if (params) {
    rb.path('definitionId', params.definitionId, {});
    rb.path('bindingId', params.bindingId, {});
    rb.path('organizationId', params.organizationId, {});
    rb.path('mappingId', params.mappingId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiWorkflowDefinitionsDefinitionIdBindingsBindingIdOrganizationsOrganizationIdMappingsMappingIdDelete.PATH = '/api/workflow/definitions/{definitionId}/bindings/{bindingId}/organizations/{organizationId}/mappings/{mappingId}';
