/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowDefinitionDto as WorkflowApplicationDtOsWorkflowDefinitionDto } from '../../models/Workflow/Application/DTOs/workflow-definition-dto';

export interface ApiWorkflowDefinitionsIdGet$Params {
  id: string;
}

export function apiWorkflowDefinitionsIdGet(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowDefinitionDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowDefinitionDto>;
    })
  );
}

apiWorkflowDefinitionsIdGet.PATH = '/api/workflow/definitions/{id}';
