/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateWorkflowDefinitionRequest as WorkflowApiControllersUpdateWorkflowDefinitionRequest } from '../../models/Workflow/Api/Controllers/update-workflow-definition-request';
import { WorkflowDefinitionDto as WorkflowApplicationDtOsWorkflowDefinitionDto } from '../../models/Workflow/Application/DTOs/workflow-definition-dto';

export interface ApiWorkflowDefinitionsIdPut$Params {
  id: string;
      body?: WorkflowApiControllersUpdateWorkflowDefinitionRequest
}

export function apiWorkflowDefinitionsIdPut(http: HttpClient, rootUrl: string, params: ApiWorkflowDefinitionsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowDefinitionDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDefinitionsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowDefinitionDto>;
    })
  );
}

apiWorkflowDefinitionsIdPut.PATH = '/api/workflow/definitions/{id}';
