/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedResultOfWorkflowIntegrationInboxMessageDto as NwfmSharedResultsPaginatedResultOfWorkflowIntegrationInboxMessageDto } from '../../models/NWFM/Shared/Results/paginated-result-of-workflow-integration-inbox-message-dto';

export interface ApiWorkflowIntegrationMessagesInboxDeadLettersGet$Params {
  page?: number;
  pageSize?: number;
}

export function apiWorkflowIntegrationMessagesInboxDeadLettersGet(http: HttpClient, rootUrl: string, params?: ApiWorkflowIntegrationMessagesInboxDeadLettersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<NwfmSharedResultsPaginatedResultOfWorkflowIntegrationInboxMessageDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowIntegrationMessagesInboxDeadLettersGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NwfmSharedResultsPaginatedResultOfWorkflowIntegrationInboxMessageDto>;
    })
  );
}

apiWorkflowIntegrationMessagesInboxDeadLettersGet.PATH = '/api/workflow/integration-messages/inbox/dead-letters';
