/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowActionCatalogEntryDto as WorkflowApplicationDtOsWorkflowActionCatalogEntryDto } from '../../models/Workflow/Application/DTOs/workflow-action-catalog-entry-dto';

export interface ApiWorkflowActionsCatalogGet$Params {
}

export function apiWorkflowActionsCatalogGet(http: HttpClient, rootUrl: string, params?: ApiWorkflowActionsCatalogGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowActionCatalogEntryDto>>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowActionsCatalogGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowActionCatalogEntryDto>>;
    })
  );
}

apiWorkflowActionsCatalogGet.PATH = '/api/workflow/actions-catalog';
