/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowIncidentDto as WorkflowApplicationDtOsWorkflowIncidentDto } from '../../models/Workflow/Application/DTOs/workflow-incident-dto';

export interface ApiWorkflowIncidentsIdGet$Params {
  id: string;
}

export function apiWorkflowIncidentsIdGet(http: HttpClient, rootUrl: string, params: ApiWorkflowIncidentsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowIncidentDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowIncidentsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowIncidentDto>;
    })
  );
}

apiWorkflowIncidentsIdGet.PATH = '/api/workflow/incidents/{id}';
