/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedResultOfWorkflowIncidentDto as NwfmSharedResultsPaginatedResultOfWorkflowIncidentDto } from '../../models/NWFM/Shared/Results/paginated-result-of-workflow-incident-dto';
import { WorkflowIncidentStatus as WorkflowDomainEnumsWorkflowIncidentStatus } from '../../models/Workflow/Domain/Enums/workflow-incident-status';

export interface ApiWorkflowIncidentsGet$Params {
  page?: number;
  pageSize?: number;
  organizationId?: string;
  status?: WorkflowDomainEnumsWorkflowIncidentStatus;
}

export function apiWorkflowIncidentsGet(http: HttpClient, rootUrl: string, params?: ApiWorkflowIncidentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<NwfmSharedResultsPaginatedResultOfWorkflowIncidentDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowIncidentsGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('organizationId', params.organizationId, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NwfmSharedResultsPaginatedResultOfWorkflowIncidentDto>;
    })
  );
}

apiWorkflowIncidentsGet.PATH = '/api/workflow/incidents';
