/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiWorkflowAssignmentGroupsIdMembersParticipantIdDelete$Params {
  id: string;
  participantId: string;
}

export function apiWorkflowAssignmentGroupsIdMembersParticipantIdDelete(http: HttpClient, rootUrl: string, params: ApiWorkflowAssignmentGroupsIdMembersParticipantIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowAssignmentGroupsIdMembersParticipantIdDelete.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('participantId', params.participantId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiWorkflowAssignmentGroupsIdMembersParticipantIdDelete.PATH = '/api/workflow/assignment-groups/{id}/members/{participantId}';
