/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateAssignmentGroupRequest as WorkflowApiControllersCreateAssignmentGroupRequest } from '../../models/Workflow/Api/Controllers/create-assignment-group-request';
import { WorkflowAssignmentGroupDto as WorkflowApplicationDtOsWorkflowAssignmentGroupDto } from '../../models/Workflow/Application/DTOs/workflow-assignment-group-dto';

export interface ApiWorkflowAssignmentGroupsPost$Params {
      body?: WorkflowApiControllersCreateAssignmentGroupRequest
}

export function apiWorkflowAssignmentGroupsPost(http: HttpClient, rootUrl: string, params?: ApiWorkflowAssignmentGroupsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowAssignmentGroupDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowAssignmentGroupsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowAssignmentGroupDto>;
    })
  );
}

apiWorkflowAssignmentGroupsPost.PATH = '/api/workflow/assignment-groups';
