/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateAssignmentGroupRequest as WorkflowApiControllersUpdateAssignmentGroupRequest } from '../../models/Workflow/Api/Controllers/update-assignment-group-request';
import { WorkflowAssignmentGroupDto as WorkflowApplicationDtOsWorkflowAssignmentGroupDto } from '../../models/Workflow/Application/DTOs/workflow-assignment-group-dto';

export interface ApiWorkflowAssignmentGroupsIdPut$Params {
  id: string;
      body?: WorkflowApiControllersUpdateAssignmentGroupRequest
}

export function apiWorkflowAssignmentGroupsIdPut(http: HttpClient, rootUrl: string, params: ApiWorkflowAssignmentGroupsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowAssignmentGroupDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowAssignmentGroupsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowAssignmentGroupDto>;
    })
  );
}

apiWorkflowAssignmentGroupsIdPut.PATH = '/api/workflow/assignment-groups/{id}';
