/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedResultOfWorkflowInstanceDto as NwfmSharedResultsPaginatedResultOfWorkflowInstanceDto } from '../../models/NWFM/Shared/Results/paginated-result-of-workflow-instance-dto';

export interface ApiWorkflowRuntimeAdminInstancesGet$Params {
  page?: number;
  pageSize?: number;
  organizationId?: string;
}

export function apiWorkflowRuntimeAdminInstancesGet(http: HttpClient, rootUrl: string, params?: ApiWorkflowRuntimeAdminInstancesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<NwfmSharedResultsPaginatedResultOfWorkflowInstanceDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRuntimeAdminInstancesGet.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('organizationId', params.organizationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NwfmSharedResultsPaginatedResultOfWorkflowInstanceDto>;
    })
  );
}

apiWorkflowRuntimeAdminInstancesGet.PATH = '/api/workflow/runtime/admin/instances';
