/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowTimerDto as WorkflowApplicationDtOsWorkflowTimerDto } from '../../models/Workflow/Application/DTOs/workflow-timer-dto';

export interface ApiWorkflowRuntimeInstancesInstanceIdTimersGet$Params {
  instanceId: string;
}

export function apiWorkflowRuntimeInstancesInstanceIdTimersGet(http: HttpClient, rootUrl: string, params: ApiWorkflowRuntimeInstancesInstanceIdTimersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowTimerDto>>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRuntimeInstancesInstanceIdTimersGet.PATH, 'get');
  if (params) {
    rb.path('instanceId', params.instanceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowTimerDto>>;
    })
  );
}

apiWorkflowRuntimeInstancesInstanceIdTimersGet.PATH = '/api/workflow/runtime/instances/{instanceId}/timers';
