/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowEventDto as WorkflowApplicationDtOsWorkflowEventDto } from '../../models/Workflow/Application/DTOs/workflow-event-dto';

export interface ApiWorkflowRuntimeInstancesInstanceIdTimelineGet$Params {
  instanceId: string;
}

export function apiWorkflowRuntimeInstancesInstanceIdTimelineGet(http: HttpClient, rootUrl: string, params: ApiWorkflowRuntimeInstancesInstanceIdTimelineGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowEventDto>>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRuntimeInstancesInstanceIdTimelineGet.PATH, 'get');
  if (params) {
    rb.path('instanceId', params.instanceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowEventDto>>;
    })
  );
}

apiWorkflowRuntimeInstancesInstanceIdTimelineGet.PATH = '/api/workflow/runtime/instances/{instanceId}/timeline';
