/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowProgressDto as WorkflowApplicationDtOsWorkflowProgressDto } from '../../models/Workflow/Application/DTOs/workflow-progress-dto';

export interface ApiWorkflowRuntimeInstancesInstanceIdProgressGet$Params {
  instanceId: string;
}

export function apiWorkflowRuntimeInstancesInstanceIdProgressGet(http: HttpClient, rootUrl: string, params: ApiWorkflowRuntimeInstancesInstanceIdProgressGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowProgressDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRuntimeInstancesInstanceIdProgressGet.PATH, 'get');
  if (params) {
    rb.path('instanceId', params.instanceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowProgressDto>;
    })
  );
}

apiWorkflowRuntimeInstancesInstanceIdProgressGet.PATH = '/api/workflow/runtime/instances/{instanceId}/progress';
