/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowLiveGraphDto as WorkflowApplicationDtOsWorkflowLiveGraphDto } from '../../models/Workflow/Application/DTOs/workflow-live-graph-dto';

export interface ApiWorkflowRuntimeInstancesInstanceIdLiveGraphGet$Params {
  instanceId: string;
}

export function apiWorkflowRuntimeInstancesInstanceIdLiveGraphGet(http: HttpClient, rootUrl: string, params: ApiWorkflowRuntimeInstancesInstanceIdLiveGraphGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowLiveGraphDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRuntimeInstancesInstanceIdLiveGraphGet.PATH, 'get');
  if (params) {
    rb.path('instanceId', params.instanceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowLiveGraphDto>;
    })
  );
}

apiWorkflowRuntimeInstancesInstanceIdLiveGraphGet.PATH = '/api/workflow/runtime/instances/{instanceId}/live-graph';
