/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowIncidentSummaryDto as WorkflowApplicationDtOsWorkflowIncidentSummaryDto } from '../../models/Workflow/Application/DTOs/workflow-incident-summary-dto';

export interface ApiWorkflowRuntimeInstancesInstanceIdIncidentsGet$Params {
  instanceId: string;
}

export function apiWorkflowRuntimeInstancesInstanceIdIncidentsGet(http: HttpClient, rootUrl: string, params: ApiWorkflowRuntimeInstancesInstanceIdIncidentsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowIncidentSummaryDto>>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRuntimeInstancesInstanceIdIncidentsGet.PATH, 'get');
  if (params) {
    rb.path('instanceId', params.instanceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkflowApplicationDtOsWorkflowIncidentSummaryDto>>;
    })
  );
}

apiWorkflowRuntimeInstancesInstanceIdIncidentsGet.PATH = '/api/workflow/runtime/instances/{instanceId}/incidents';
