/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiWorkflowRuntimeInstancesInstanceIdSuspendPost$Params {
  instanceId: string;
}

export function apiWorkflowRuntimeInstancesInstanceIdSuspendPost(http: HttpClient, rootUrl: string, params: ApiWorkflowRuntimeInstancesInstanceIdSuspendPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRuntimeInstancesInstanceIdSuspendPost.PATH, 'post');
  if (params) {
    rb.path('instanceId', params.instanceId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiWorkflowRuntimeInstancesInstanceIdSuspendPost.PATH = '/api/workflow/runtime/instances/{instanceId}/suspend';
