/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkflowInstanceDto as WorkflowApplicationDtOsWorkflowInstanceDto } from '../../models/Workflow/Application/DTOs/workflow-instance-dto';

export interface ApiWorkflowRuntimeInstancesInstanceIdGet$Params {
  instanceId: string;
}

export function apiWorkflowRuntimeInstancesInstanceIdGet(http: HttpClient, rootUrl: string, params: ApiWorkflowRuntimeInstancesInstanceIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowInstanceDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRuntimeInstancesInstanceIdGet.PATH, 'get');
  if (params) {
    rb.path('instanceId', params.instanceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowInstanceDto>;
    })
  );
}

apiWorkflowRuntimeInstancesInstanceIdGet.PATH = '/api/workflow/runtime/instances/{instanceId}';
