/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StartWorkflowInstanceRequest as WorkflowApiControllersStartWorkflowInstanceRequest } from '../../models/Workflow/Api/Controllers/start-workflow-instance-request';
import { WorkflowInstanceDto as WorkflowApplicationDtOsWorkflowInstanceDto } from '../../models/Workflow/Application/DTOs/workflow-instance-dto';

export interface ApiWorkflowRuntimeInstancesPost$Params {
      body?: WorkflowApiControllersStartWorkflowInstanceRequest
}

export function apiWorkflowRuntimeInstancesPost(http: HttpClient, rootUrl: string, params?: ApiWorkflowRuntimeInstancesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowInstanceDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowRuntimeInstancesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowInstanceDto>;
    })
  );
}

apiWorkflowRuntimeInstancesPost.PATH = '/api/workflow/runtime/instances';
