/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ParticipantContextDto as NwfmApiControllersParticipantContextDto } from '../../../../models/NWFM/Api/Controllers/participant-context-dto';
import { TenantDto as NwfmApiControllersTenantDto } from '../../../../models/NWFM/Api/Controllers/tenant-dto';
export interface AppContextDto {
  defaultParticipantId?: string;
  participants?: Array<NwfmApiControllersParticipantContextDto> | null;
  tenant?: NwfmApiControllersTenantDto;
}
