/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ParticipantContextDto {
  actorId?: string;
  displayName?: string | null;
  displayNameAr?: string | null;
  id?: string;
}
