/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DayOfWeek as SystemDayOfWeek } from '../../../../models/System/day-of-week';
export interface AddCalendarPeriodRequest {
  dayOfWeek?: SystemDayOfWeek;
  endTime?: string;
  isWorkingTime?: boolean;
  startTime?: string;
}
