/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddGroupMemberRequest {
  canClaim?: boolean;
  isPrimary?: boolean;
  participantId?: string;
  validFrom?: string | null;
  validTo?: string | null;
}
