/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddCalendarHolidayRequest {
  holidayDate?: string;
  isRecurring?: boolean;
  name?: string | null;
  nameAr?: string | null;
}
