/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompleteWorkItemRequest {
  actionTaken?: string | null;
  comment?: string | null;
  redirectAssignmentGroupId?: string | null;
  redirectDepartmentId?: string | null;
}
