/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateWorkflowBindingAssignmentMappingRequest {
  assignmentGroupId?: string;
  assignmentKey?: string | null;
}
