/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateBusinessCalendarRequest {
  code?: string | null;
  name?: string | null;
  nameAr?: string | null;
  organizationId?: string | null;
  timeZone?: string | null;
}
