/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterParticipantRequest {
  displayName?: string | null;
  displayNameAr?: string | null;
  email?: string | null;
  employeeNumber?: string | null;
}
