/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StartWorkflowInstanceRequest {
  businessEntityId?: string | null;
  correlationId?: string | null;
  idempotencyKey?: string | null;
  workflowBindingId?: string;
}
