/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssignmentStrategy as WorkflowDomainEnumsAssignmentStrategy } from '../../../../models/Workflow/Domain/Enums/assignment-strategy';
export interface UpdateAssignmentGroupRequest {
  assignmentStrategy?: WorkflowDomainEnumsAssignmentStrategy;
  code?: string | null;
  name?: string | null;
  nameAr?: string | null;
}
