/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowBindingMode as WorkflowDomainEnumsWorkflowBindingMode } from '../../../../models/Workflow/Domain/Enums/workflow-binding-mode';
import { WorkflowExecutionPolicy as WorkflowDomainEnumsWorkflowExecutionPolicy } from '../../../../models/Workflow/Domain/Enums/workflow-execution-policy';
import { WorkflowVersionPolicy as WorkflowDomainEnumsWorkflowVersionPolicy } from '../../../../models/Workflow/Domain/Enums/workflow-version-policy';
export interface UpdateWorkflowBindingRequest {
  conditionJson?: string | null;
  description?: string | null;
  entityType?: string | null;
  executionPolicy?: WorkflowDomainEnumsWorkflowExecutionPolicy;
  fixedWorkflowVersionId?: string | null;
  inputMappingJson?: string | null;
  mode?: WorkflowDomainEnumsWorkflowBindingMode;
  moduleKey?: string | null;
  outcomeMappingJson?: string | null;
  screenKey?: string | null;
  startConditionExpression?: string | null;
  startEventKey?: string | null;
  triggerEvent?: string | null;
  versionPolicy?: WorkflowDomainEnumsWorkflowVersionPolicy;
}
