/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateBusinessCalendarRequest {
  isActive?: boolean;
  name?: string | null;
  nameAr?: string | null;
  timeZone?: string | null;
}
