/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateDepartmentRequest {
  code?: string | null;
  defaultAssignmentGroupId?: string | null;
  name?: string | null;
  nameAr?: string | null;
}
