/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateWorkflowDefinitionRequest {
  description?: string | null;
  descriptionAr?: string | null;
  name?: string | null;
  nameAr?: string | null;
}
