/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowRequestDto as WorkflowApplicationDtOsWorkflowRequestDto } from '../../../../../models/Workflow/Application/DTOs/workflow-request-dto';
import { WorkflowRequestKpiDto as WorkflowApplicationDtOsWorkflowRequestKpiDto } from '../../../../../models/Workflow/Application/DTOs/workflow-request-kpi-dto';
export interface WorkflowRequestPageDto {
  items?: Array<WorkflowApplicationDtOsWorkflowRequestDto> | null;
  kpis?: WorkflowApplicationDtOsWorkflowRequestKpiDto;
  pageNumber?: number;
  pageSize?: number;
  totalCount?: number;
}
