namespace Workflow.Domain.Enums;

public enum WorkflowEventType
{
    InstanceStarted     = 0,
    InstanceCompleted   = 1,
    InstanceCancelled   = 2,
    InstanceFailed      = 3,
    ActivityStarted     = 4,
    ActivityCompleted   = 5,
    ActivityFailed      = 6,
    WorkItemClaimed     = 7,
    WorkItemCompleted   = 8,
    WorkItemCancelled   = 9,
    TransitionTaken     = 10,
    VariableSet         = 11,
    InstanceSuspended   = 12,
    InstanceResumed     = 13,
    WorkItemReleased    = 14,
    TimerScheduled      = 15,
    TimerFired          = 16,
    NotificationQueued  = 17,
    NotificationFailed  = 18,
    ServiceTaskExecuted = 19,
    ParallelBranchStarted = 20,
    ParallelBranchCompleted = 21,
    JoinCompleted       = 22,
    IncidentOpened      = 23,
    IncidentResolved    = 24,
    ReminderSent        = 25,
    EscalationApplied   = 26,
    OutcomePublished    = 27,
    CandidateAssigned   = 28,
    WorkItemReassigned  = 29,
    WorkItemDelegated   = 30,
}
