/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateDepartmentRequest as WorkflowApiControllersUpdateDepartmentRequest } from '../../models/Workflow/Api/Controllers/update-department-request';
import { WorkflowDepartmentDto as WorkflowApplicationDtOsWorkflowDepartmentDto } from '../../models/Workflow/Application/DTOs/workflow-department-dto';

export interface ApiWorkflowDepartmentsIdPut$Params {
  id: string;
      body?: WorkflowApiControllersUpdateDepartmentRequest
}

export function apiWorkflowDepartmentsIdPut(http: HttpClient, rootUrl: string, params: ApiWorkflowDepartmentsIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowDepartmentDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDepartmentsIdPut.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowDepartmentDto>;
    })
  );
}

apiWorkflowDepartmentsIdPut.PATH = '/api/workflow/departments/{id}';
