/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddDepartmentMemberRequest as WorkflowApiControllersAddDepartmentMemberRequest } from '../../models/Workflow/Api/Controllers/add-department-member-request';
import { WorkflowDepartmentMemberDto as WorkflowApplicationDtOsWorkflowDepartmentMemberDto } from '../../models/Workflow/Application/DTOs/workflow-department-member-dto';

export interface ApiWorkflowDepartmentsIdMembersPost$Params {
  id: string;
      body?: WorkflowApiControllersAddDepartmentMemberRequest
}

export function apiWorkflowDepartmentsIdMembersPost(http: HttpClient, rootUrl: string, params: ApiWorkflowDepartmentsIdMembersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowDepartmentMemberDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDepartmentsIdMembersPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowDepartmentMemberDto>;
    })
  );
}

apiWorkflowDepartmentsIdMembersPost.PATH = '/api/workflow/departments/{id}/members';
