/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateDepartmentRequest as WorkflowApiControllersCreateDepartmentRequest } from '../../models/Workflow/Api/Controllers/create-department-request';
import { WorkflowDepartmentDto as WorkflowApplicationDtOsWorkflowDepartmentDto } from '../../models/Workflow/Application/DTOs/workflow-department-dto';

export interface ApiWorkflowDepartmentsPost$Params {
      body?: WorkflowApiControllersCreateDepartmentRequest
}

export function apiWorkflowDepartmentsPost(http: HttpClient, rootUrl: string, params?: ApiWorkflowDepartmentsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkflowApplicationDtOsWorkflowDepartmentDto>> {
  const rb = new RequestBuilder(rootUrl, apiWorkflowDepartmentsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkflowApplicationDtOsWorkflowDepartmentDto>;
    })
  );
}

apiWorkflowDepartmentsPost.PATH = '/api/workflow/departments';
