/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivityOutcomeDefinitionDto {
  activityDefinitionId?: string;
  description?: string | null;
  descriptionAr?: string | null;
  id?: string;
  isActive?: boolean;
  isDefault?: boolean;
  name?: string | null;
  nameAr?: string | null;
  outcomeKey?: string | null;
  requiresAttachment?: boolean;
  requiresComment?: boolean;
  resultValue?: string | null;
  sortOrder?: number;
}
