/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityInstanceStatus as WorkflowDomainEnumsActivityInstanceStatus } from '../../../../models/Workflow/Domain/Enums/activity-instance-status';
import { ActivityType as WorkflowDomainEnumsActivityType } from '../../../../models/Workflow/Domain/Enums/activity-type';
export interface ActivityInstanceDto {
  activityNodeKey?: string | null;
  activityType?: WorkflowDomainEnumsActivityType;
  completedAt?: string | null;
  failedAt?: string | null;
  failureReason?: string | null;
  id?: string;
  name?: string | null;
  startedAt?: string;
  status?: WorkflowDomainEnumsActivityInstanceStatus;
  workflowInstanceId?: string;
}
