/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityActionDefinitionDto as WorkflowApplicationDtOsActivityActionDefinitionDto } from '../../../../models/Workflow/Application/DTOs/activity-action-definition-dto';
import { ActivityAssignmentRuleDto as WorkflowApplicationDtOsActivityAssignmentRuleDto } from '../../../../models/Workflow/Application/DTOs/activity-assignment-rule-dto';
import { ActivityOutcomeDefinitionDto as WorkflowApplicationDtOsActivityOutcomeDefinitionDto } from '../../../../models/Workflow/Application/DTOs/activity-outcome-definition-dto';
import { ActivityType as WorkflowDomainEnumsActivityType } from '../../../../models/Workflow/Domain/Enums/activity-type';
export interface ActivityDefinitionDto {
  actionKey?: string | null;
  actions?: Array<WorkflowApplicationDtOsActivityActionDefinitionDto> | null;
  activityType?: WorkflowDomainEnumsActivityType;
  assignmentRules?: Array<WorkflowApplicationDtOsActivityAssignmentRuleDto> | null;
  configurationJson?: string | null;
  id?: string;
  name?: string | null;
  nameAr?: string | null;
  nodeKey?: string | null;
  outcomes?: Array<WorkflowApplicationDtOsActivityOutcomeDefinitionDto> | null;
  positionX?: number | null;
  positionY?: number | null;
  workflowVersionId?: string;
}
