/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActionExecutionTrigger as WorkflowDomainEnumsActionExecutionTrigger } from '../../../../models/Workflow/Domain/Enums/action-execution-trigger';
import { ActionFailurePolicy as WorkflowDomainEnumsActionFailurePolicy } from '../../../../models/Workflow/Domain/Enums/action-failure-policy';
export interface ActivityActionDefinitionDto {
  actionKey?: string | null;
  activityDefinitionId?: string;
  conditionExpression?: string | null;
  executionTrigger?: WorkflowDomainEnumsActionExecutionTrigger;
  failurePolicy?: WorkflowDomainEnumsActionFailurePolicy;
  id?: string;
  inputMappingJson?: string | null;
  isActive?: boolean;
  outcomeKey?: string | null;
  outputMappingJson?: string | null;
  retryCount?: number;
  retryDelaySeconds?: number;
  sequence?: number;
  timeoutSeconds?: number;
}
