/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssigneeType as WorkflowDomainEnumsAssigneeType } from '../../../../models/Workflow/Domain/Enums/assignee-type';
export interface ActivityAssignmentRuleDto {
  activityDefinitionId?: string;
  assigneeType?: WorkflowDomainEnumsAssigneeType;
  assignmentKey?: string | null;
  assignmentPurpose?: string | null;
  expression?: string | null;
  id?: string;
  isActive?: boolean;
  isFallback?: boolean;
  priority?: number;
  referenceId?: string | null;
}
