/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DayOfWeek as SystemDayOfWeek } from '../../../../models/System/day-of-week';
export interface BusinessCalendarPeriodDto {
  calendarId?: string;
  dayOfWeek?: SystemDayOfWeek;
  endTime?: string;
  id?: string;
  isWorkingTime?: boolean;
  startTime?: string;
}
