/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BusinessCalendarHolidayDto as WorkflowApplicationDtOsBusinessCalendarHolidayDto } from '../../../../models/Workflow/Application/DTOs/business-calendar-holiday-dto';
import { BusinessCalendarPeriodDto as WorkflowApplicationDtOsBusinessCalendarPeriodDto } from '../../../../models/Workflow/Application/DTOs/business-calendar-period-dto';
export interface BusinessCalendarDto {
  code?: string | null;
  createdAt?: string;
  holidays?: Array<WorkflowApplicationDtOsBusinessCalendarHolidayDto> | null;
  id?: string;
  isActive?: boolean;
  name?: string | null;
  nameAr?: string | null;
  organizationId?: string | null;
  periods?: Array<WorkflowApplicationDtOsBusinessCalendarPeriodDto> | null;
  timeZone?: string | null;
  updatedAt?: string | null;
}
