/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BusinessCalendarHolidayDto {
  calendarId?: string;
  holidayDate?: string;
  id?: string;
  isRecurring?: boolean;
  name?: string | null;
  nameAr?: string | null;
}
