/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SlaDurationUnit as WorkflowDomainEnumsSlaDurationUnit } from '../../../../models/Workflow/Domain/Enums/sla-duration-unit';
export interface SlaPolicyDto {
  businessCalendarId?: string;
  createdAt?: string;
  duration?: number;
  durationUnit?: WorkflowDomainEnumsSlaDurationUnit;
  escalationAssignmentKey?: string | null;
  escalationThresholdsJson?: string | null;
  id?: string;
  isActive?: boolean;
  name?: string | null;
  nameAr?: string | null;
  organizationId?: string | null;
  policyCode?: string | null;
  reminderThresholdsJson?: string | null;
  updatedAt?: string | null;
}
