/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowTimerStatus as WorkflowDomainEnumsWorkflowTimerStatus } from '../../../../models/Workflow/Domain/Enums/workflow-timer-status';
import { WorkflowTimerType as WorkflowDomainEnumsWorkflowTimerType } from '../../../../models/Workflow/Domain/Enums/workflow-timer-type';
export interface WorkflowTimerDto {
  activityInstanceId?: string;
  attemptCount?: number;
  cancelledAt?: string | null;
  completedAt?: string | null;
  createdAt?: string;
  dueAt?: string;
  id?: string;
  lastAttemptAt?: string | null;
  organizationId?: string;
  signalKey?: string | null;
  status?: WorkflowDomainEnumsWorkflowTimerStatus;
  timerType?: WorkflowDomainEnumsWorkflowTimerType;
  workflowInstanceId?: string;
}
