/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowBindingAssignmentMappingDto {
  assignmentGroupId?: string;
  assignmentGroupName?: string | null;
  assignmentKey?: string | null;
  createdAt?: string;
  id?: string;
  isActive?: boolean;
  organizationId?: string;
  updatedAt?: string;
  workflowBindingId?: string;
}
