/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowDepartmentDto {
  code?: string | null;
  createdAt?: string;
  defaultAssignmentGroupId?: string | null;
  id?: string;
  isActive?: boolean;
  memberCount?: number;
  name?: string | null;
  nameAr?: string | null;
  organizationId?: string;
  updatedAt?: string;
}
