/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowPublishPreviewDto {
  activityCount?: number;
  blockingReasons?: Array<string> | null;
  canPublish?: boolean;
  changeSummary?: string | null;
  latestPublishedVersionId?: string | null;
  latestPublishedVersionNumber?: number | null;
  requiredAssignmentKeys?: Array<string> | null;
  status?: string | null;
  transitionCount?: number;
  validationStatus?: string | null;
  variableCount?: number;
  versionId?: string;
  versionNumber?: number;
  warnings?: Array<string> | null;
  workflowDefinitionId?: string;
}
