/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowLiveGraphEdgeDto {
  fromNodeKey?: string | null;
  isDefault?: boolean;
  toNodeKey?: string | null;
}
