/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowTransitionDto {
  conditionExpression?: string | null;
  fromActivityDefinitionId?: string;
  id?: string;
  isDefault?: boolean;
  priority?: number;
  toActivityDefinitionId?: string;
  transitionKey?: string | null;
  workflowVersionId?: string;
}
