/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowNotificationLogDto as WorkflowApplicationDtOsWorkflowNotificationLogDto } from '../../../../models/Workflow/Application/DTOs/workflow-notification-log-dto';
export interface WorkflowNotificationLogPageDto {
  items?: Array<WorkflowApplicationDtOsWorkflowNotificationLogDto> | null;
  pageNumber?: number;
  pageSize?: number;
  totalCount?: number;
}
