/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowDepartmentMemberDto {
  displayName?: string | null;
  displayNameAr?: string | null;
  email?: string | null;
  id?: string;
  participantId?: string;
}
