/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowIntegrationOutboxMessageDto {
  attemptCount?: number;
  businessEntityId?: string | null;
  businessEntityType?: string | null;
  createdAt?: string;
  id?: string;
  messageId?: string | null;
  moduleKey?: string | null;
  organizationId?: string;
  outcomeKey?: string | null;
  status?: string | null;
  updatedAt?: string;
}
