/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowActionCatalogEntryDto {
  actionKey?: string | null;
  moduleKey?: string | null;
  nameAr?: string | null;
  nameEn?: string | null;
}
