/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowSimulationStepDto {
  activityType?: string | null;
  nodeKey?: string | null;
  note?: string | null;
}
