/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkloadGroupDto {
  claimedCount?: number;
  groupId?: string;
  name?: string | null;
  overdueCount?: number;
  pendingCount?: number;
}
