/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkloadGroupDto as WorkflowApplicationDtOsWorkloadGroupDto } from '../../../../models/Workflow/Application/DTOs/workload-group-dto';
import { WorkloadTotalsDto as WorkflowApplicationDtOsWorkloadTotalsDto } from '../../../../models/Workflow/Application/DTOs/workload-totals-dto';
export interface WorkloadDashboardDto {
  groups?: Array<WorkflowApplicationDtOsWorkloadGroupDto> | null;
  totals?: WorkflowApplicationDtOsWorkloadTotalsDto;
}
