/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowValidationStatus as WorkflowDomainEnumsWorkflowValidationStatus } from '../../../../models/Workflow/Domain/Enums/workflow-validation-status';
import { WorkflowVersionStatus as WorkflowDomainEnumsWorkflowVersionStatus } from '../../../../models/Workflow/Domain/Enums/workflow-version-status';
export interface WorkflowVersionDto {
  workspaceJson?: string | null;
  pinnedChildVersionsJson?: string | null;
  changeSummary?: string | null;
  createdAt?: string;
  createdByUserId?: string;
  id?: string;
  publishedAt?: string | null;
  publishedByUserId?: string | null;
  schemaVersion?: string | null;
  status?: WorkflowDomainEnumsWorkflowVersionStatus;
  updatedAt?: string;
  validationStatus?: WorkflowDomainEnumsWorkflowValidationStatus;
  versionNumber?: number;
  workflowDefinitionId?: string;
}
