/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowInstanceStatus as WorkflowDomainEnumsWorkflowInstanceStatus } from '../../../../models/Workflow/Domain/Enums/workflow-instance-status';
export interface WorkflowRequestDto {
  businessEntityId?: string | null;
  businessEntityType?: string | null;
  completedAtUtc?: string | null;
  correlationId?: string | null;
  createdAt?: string;
  currentActivityInstanceId?: string | null;
  currentActivityNameAr?: string | null;
  currentActivityNameEn?: string | null;
  currentAssignedGroupId?: string | null;
  currentAssignedGroupName?: string | null;
  currentClaimedByUserId?: string | null;
  currentTaskDueAtUtc?: string | null;
  currentTaskSlaMinutes?: number | null;
  id?: string;
  organizationId?: string;
  originalAssignedGroupId?: string | null;
  originalAssignedGroupName?: string | null;
  remainingSlaMinutes?: number | null;
  requestDate?: string;
  requestNumber?: string | null;
  requesterUserId?: string | null;
  screenKey?: string | null;
  serviceKey?: string | null;
  serviceNameAr?: string | null;
  serviceNameEn?: string | null;
  status?: WorkflowDomainEnumsWorkflowInstanceStatus;
  triggerEventKey?: string | null;
  updatedAt?: string;
  workflowBindingId?: string;
  workflowInstanceId?: string;
}
