/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowBindingMode as WorkflowDomainEnumsWorkflowBindingMode } from '../../../../models/Workflow/Domain/Enums/workflow-binding-mode';
import { WorkflowExecutionPolicy as WorkflowDomainEnumsWorkflowExecutionPolicy } from '../../../../models/Workflow/Domain/Enums/workflow-execution-policy';
import { WorkflowVersionPolicy as WorkflowDomainEnumsWorkflowVersionPolicy } from '../../../../models/Workflow/Domain/Enums/workflow-version-policy';
export interface WorkflowBindingDto {
  conditionJson?: string | null;
  createdAt?: string;
  description?: string | null;
  entityType?: string | null;
  executionPolicy?: WorkflowDomainEnumsWorkflowExecutionPolicy;
  fixedWorkflowVersionId?: string | null;
  id?: string;
  inputMappingJson?: string | null;
  isActive?: boolean;
  mode?: WorkflowDomainEnumsWorkflowBindingMode;
  moduleKey?: string | null;
  organizationId?: string;
  outcomeMappingJson?: string | null;
  screenKey?: string | null;
  startConditionExpression?: string | null;
  startEventKey?: string | null;
  triggerEvent?: string | null;
  updatedAt?: string;
  versionPolicy?: WorkflowDomainEnumsWorkflowVersionPolicy;
  workflowDefinitionId?: string;
  workflowDefinitionName?: string | null;
}
