/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityInstanceDto as WorkflowApplicationDtOsActivityInstanceDto } from '../../../../models/Workflow/Application/DTOs/activity-instance-dto';
import { WorkflowEventDto as WorkflowApplicationDtOsWorkflowEventDto } from '../../../../models/Workflow/Application/DTOs/workflow-event-dto';
import { WorkflowInstanceDto as WorkflowApplicationDtOsWorkflowInstanceDto } from '../../../../models/Workflow/Application/DTOs/workflow-instance-dto';
export interface WorkflowProgressDto {
  activities?: Array<WorkflowApplicationDtOsActivityInstanceDto> | null;
  events?: Array<WorkflowApplicationDtOsWorkflowEventDto> | null;
  instance?: WorkflowApplicationDtOsWorkflowInstanceDto;
}
