/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowDefinitionDto {
  createdAt?: string;
  definitionKey?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  id?: string;
  isActive?: boolean;
  name?: string | null;
  nameAr?: string | null;
  organizationId?: string;
  updatedAt?: string;
  versionCount?: number;
}
