/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowGroupMemberDto as WorkflowApplicationDtOsWorkflowGroupMemberDto } from '../../../../models/Workflow/Application/DTOs/workflow-group-member-dto';
import { AssignmentStrategy as WorkflowDomainEnumsAssignmentStrategy } from '../../../../models/Workflow/Domain/Enums/assignment-strategy';
export interface WorkflowAssignmentGroupDetailDto {
  assignmentStrategy?: WorkflowDomainEnumsAssignmentStrategy;
  code?: string | null;
  createdAt?: string;
  id?: string;
  isActive?: boolean;
  members?: Array<WorkflowApplicationDtOsWorkflowGroupMemberDto> | null;
  name?: string | null;
  nameAr?: string | null;
  organizationId?: string;
  updatedAt?: string;
}
