/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowParticipantDto {
  createdAt?: string;
  displayName?: string | null;
  displayNameAr?: string | null;
  email?: string | null;
  employeeNumber?: string | null;
  id?: string;
  isActive?: boolean;
  organizationId?: string;
  updatedAt?: string;
  userId?: string;
}
