/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowBindingReadinessDto {
  bindingId?: string;
  blockingReason?: string | null;
  isReady?: boolean;
  mappedAssignmentKeys?: Array<string> | null;
  organizationId?: string;
  requiredAssignmentKeys?: Array<string> | null;
  resolvedVersionId?: string | null;
  unmappedAssignmentKeys?: Array<string> | null;
}
