/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityDefinitionDto as WorkflowApplicationDtOsActivityDefinitionDto } from '../../../../models/Workflow/Application/DTOs/activity-definition-dto';
import { WorkflowTransitionDto as WorkflowApplicationDtOsWorkflowTransitionDto } from '../../../../models/Workflow/Application/DTOs/workflow-transition-dto';
import { WorkflowVariableDefinitionDto as WorkflowApplicationDtOsWorkflowVariableDefinitionDto } from '../../../../models/Workflow/Application/DTOs/workflow-variable-definition-dto';
import { WorkflowValidationStatus as WorkflowDomainEnumsWorkflowValidationStatus } from '../../../../models/Workflow/Domain/Enums/workflow-validation-status';
import { WorkflowVersionStatus as WorkflowDomainEnumsWorkflowVersionStatus } from '../../../../models/Workflow/Domain/Enums/workflow-version-status';
export interface WorkflowVersionDetailDto {
  workspaceJson?: string | null;
  pinnedChildVersionsJson?: string | null;
  activities?: Array<WorkflowApplicationDtOsActivityDefinitionDto> | null;
  changeSummary?: string | null;
  createdAt?: string;
  createdByUserId?: string;
  designerJson?: string | null;
  id?: string;
  publishedAt?: string | null;
  publishedByUserId?: string | null;
  schemaVersion?: string | null;
  status?: WorkflowDomainEnumsWorkflowVersionStatus;
  transitions?: Array<WorkflowApplicationDtOsWorkflowTransitionDto> | null;
  updatedAt?: string;
  validationResultJson?: string | null;
  validationStatus?: WorkflowDomainEnumsWorkflowValidationStatus;
  variables?: Array<WorkflowApplicationDtOsWorkflowVariableDefinitionDto> | null;
  versionNumber?: number;
  workflowDefinitionId?: string;
}
