/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowNotificationLogStatus as WorkflowDomainEnumsWorkflowNotificationLogStatus } from '../../../../models/Workflow/Domain/Enums/workflow-notification-log-status';
export interface WorkflowNotificationLogDto {
  channels?: string | null;
  correlationId?: string | null;
  createdAt?: string;
  id?: string;
  organizationId?: string;
  status?: WorkflowDomainEnumsWorkflowNotificationLogStatus;
  templateKey?: string | null;
  variablesJsonTruncated?: string | null;
}
