/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowValidationIssueDto {
  code?: string | null;
  message?: string | null;
  nodeKey?: string | null;
}
