/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowLiveGraphNodeDto {
  activityType?: string | null;
  name?: string | null;
  nodeKey?: string | null;
  runtimeStatus?: string | null;
  x?: number;
  y?: number;
}
