/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowEventType as WorkflowDomainEnumsWorkflowEventType } from '../../../../models/Workflow/Domain/Enums/workflow-event-type';
export interface WorkflowEventDto {
  actionTaken?: string | null;
  activityNameAr?: string | null;
  activityNameEn?: string | null;
  activityNodeKey?: string | null;
  actorName?: string | null;
  actorNameAr?: string | null;
  actorUserId?: string | null;
  attachmentName?: string | null;
  attachmentUrl?: string | null;
  comment?: string | null;
  eventType?: WorkflowDomainEnumsWorkflowEventType;
  id?: string;
  occurredAt?: string;
  payloadJson?: string | null;
  workflowInstanceId?: string;
}
