/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActivityOutcomeDefinitionDto as WorkflowApplicationDtOsActivityOutcomeDefinitionDto } from '../../../../models/Workflow/Application/DTOs/activity-outcome-definition-dto';
import { WorkItemStatus as WorkflowDomainEnumsWorkItemStatus } from '../../../../models/Workflow/Domain/Enums/work-item-status';
export interface WorkItemDto {
  actionTaken?: string | null;
  activityInstanceId?: string;
  assignmentGroupId?: string;
  assignmentGroupName?: string | null;
  availableOutcomes?: Array<WorkflowApplicationDtOsActivityOutcomeDefinitionDto> | null;
  claimedAt?: string | null;
  claimedByUserId?: string | null;
  commentText?: string | null;
  completedAt?: string | null;
  completedByUserId?: string | null;
  createdAt?: string;
  currentStepNameAr?: string | null;
  currentStepNameEn?: string | null;
  dueAt?: string | null;
  id?: string;
  organizationId?: string;
  originalGroupName?: string | null;
  remainingSlaMinutes?: number | null;
  requestDate?: string | null;
  requestNumber?: string | null;
  serviceNameAr?: string | null;
  serviceNameEn?: string | null;
  slaDurationMinutes?: number | null;
  status?: WorkflowDomainEnumsWorkItemStatus;
  updatedAt?: string;
  workflowInstanceId?: string;
}
