/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssignmentStrategy as WorkflowDomainEnumsAssignmentStrategy } from '../../../../models/Workflow/Domain/Enums/assignment-strategy';
export interface WorkflowAssignmentGroupDto {
  assignmentStrategy?: WorkflowDomainEnumsAssignmentStrategy;
  code?: string | null;
  createdAt?: string;
  id?: string;
  isActive?: boolean;
  memberCount?: number;
  name?: string | null;
  nameAr?: string | null;
  organizationId?: string;
  updatedAt?: string;
}
