/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VariableDataType as WorkflowDomainEnumsVariableDataType } from '../../../../models/Workflow/Domain/Enums/variable-data-type';
export interface WorkflowVariableDefinitionDto {
  dataType?: WorkflowDomainEnumsVariableDataType;
  defaultValue?: string | null;
  description?: string | null;
  descriptionAr?: string | null;
  id?: string;
  isRequired?: boolean;
  isSensitive?: boolean;
  name?: string | null;
  nameAr?: string | null;
  variableKey?: string | null;
  workflowVersionId?: string;
}
