/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowRequestKpiDto {
  breached?: number;
  completed?: number;
  inProgress?: number;
  total?: number;
}
