/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowInstanceStatus as WorkflowDomainEnumsWorkflowInstanceStatus } from '../../../../models/Workflow/Domain/Enums/workflow-instance-status';
export interface WorkflowInstanceDto {
  businessEntityId?: string | null;
  cancelledAt?: string | null;
  completedAt?: string | null;
  correlationId?: string | null;
  createdAt?: string;
  currentActivityNodeKey?: string | null;
  failureReason?: string | null;
  id?: string;
  idempotencyKey?: string | null;
  organizationId?: string;
  pinnedWorkflowVersionId?: string;
  startedAt?: string;
  startedByUserId?: string | null;
  status?: WorkflowDomainEnumsWorkflowInstanceStatus;
  suspendedAt?: string | null;
  updatedAt?: string;
  workflowBindingId?: string;
}
