/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowIncidentSeverity as WorkflowDomainEnumsWorkflowIncidentSeverity } from '../../../../models/Workflow/Domain/Enums/workflow-incident-severity';
import { WorkflowIncidentStatus as WorkflowDomainEnumsWorkflowIncidentStatus } from '../../../../models/Workflow/Domain/Enums/workflow-incident-status';
import { WorkflowIncidentType as WorkflowDomainEnumsWorkflowIncidentType } from '../../../../models/Workflow/Domain/Enums/workflow-incident-type';
export interface WorkflowIncidentSummaryDto {
  createdAt?: string;
  errorCode?: string | null;
  id?: string;
  incidentType?: WorkflowDomainEnumsWorkflowIncidentType;
  severity?: WorkflowDomainEnumsWorkflowIncidentSeverity;
  status?: WorkflowDomainEnumsWorkflowIncidentStatus;
  title?: string | null;
}
