/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkflowGroupMemberDto {
  canClaim?: boolean;
  displayName?: string | null;
  displayNameAr?: string | null;
  email?: string | null;
  id?: string;
  isPrimary?: boolean;
  participantId?: string;
  validFrom?: string | null;
  validTo?: string | null;
}
