/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowLiveGraphEdgeDto as WorkflowApplicationDtOsWorkflowLiveGraphEdgeDto } from '../../../../models/Workflow/Application/DTOs/workflow-live-graph-edge-dto';
import { WorkflowLiveGraphNodeDto as WorkflowApplicationDtOsWorkflowLiveGraphNodeDto } from '../../../../models/Workflow/Application/DTOs/workflow-live-graph-node-dto';
export interface WorkflowLiveGraphDto {
  currentNodeKey?: string | null;
  edges?: Array<WorkflowApplicationDtOsWorkflowLiveGraphEdgeDto> | null;
  instanceStatus?: string | null;
  nodes?: Array<WorkflowApplicationDtOsWorkflowLiveGraphNodeDto> | null;
}
