/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WorkflowIncidentSeverity as WorkflowDomainEnumsWorkflowIncidentSeverity } from '../../../../models/Workflow/Domain/Enums/workflow-incident-severity';
import { WorkflowIncidentStatus as WorkflowDomainEnumsWorkflowIncidentStatus } from '../../../../models/Workflow/Domain/Enums/workflow-incident-status';
import { WorkflowIncidentType as WorkflowDomainEnumsWorkflowIncidentType } from '../../../../models/Workflow/Domain/Enums/workflow-incident-type';
export interface WorkflowIncidentDto {
  activityInstanceId?: string | null;
  activityNodeKey?: string | null;
  createdAt?: string;
  errorCode?: string | null;
  errorMessage?: string | null;
  id?: string;
  ignoredAt?: string | null;
  ignoredByUserId?: string | null;
  incidentType?: WorkflowDomainEnumsWorkflowIncidentType;
  organizationId?: string;
  resolutionNotes?: string | null;
  resolvedAt?: string | null;
  resolvedByUserId?: string | null;
  severity?: WorkflowDomainEnumsWorkflowIncidentSeverity;
  status?: WorkflowDomainEnumsWorkflowIncidentStatus;
  title?: string | null;
  updatedAt?: string | null;
  workflowInstanceId?: string;
}
