/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppContextDto as NwfmApiControllersAppContextDto } from '../../models/NWFM/Api/Controllers/app-context-dto';

export interface ApiAppContextGet$Json$Params {
}

export function apiAppContextGet$Json(http: HttpClient, rootUrl: string, params?: ApiAppContextGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<NwfmApiControllersAppContextDto>> {
  const rb = new RequestBuilder(rootUrl, apiAppContextGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NwfmApiControllersAppContextDto>;
    })
  );
}

apiAppContextGet$Json.PATH = '/api/app-context';
